server:
  port:8082

spring:
  application.name: inventory-service
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:29092}
    consumer:
      group-id: {$KAFKA_GROUP_ID:orderflow-inventory}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.orderflow.*"
        spring.json.value.default.type: "com.orderflow.common.events.OrderEvent"
        spring.json.use.type.headers: false
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info